name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  # Use a repo-local NuGet cache for speed & isolation
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet: ['8.0.x']  # add '6.0.x'/'7.0.x' if you multi-target
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
          cache: true  # enables NuGet cache

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --no-restore -c Release /warnaserror

      - name: Test (with coverage)
        run: dotnet test --no-build -c Release --collect "XPlat Code Coverage" --logger "trx;LogFileName=test-results.trx"

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.dotnet }}
          path: |
            **/TestResults/*.trx
            **/TestResults/*/coverage.cobertura.xml
          if-no-files-found: ignore